branch-defaults:
  master:
    environment: strive-main-production
global:
  application_name: madetostrive.com
  default_ec2_keyname: strive.com-prod
  default_platform: PHP
  default_region: us-west-2
  profile: eb-cli-strive
  sc: git
