branch-defaults:
  master:
    environment: strive-main-production
    group_suffix: null
global:
  application_name: madetostrive.com
  branch: null
  default_ec2_keyname: strive.com-prod
  default_platform: python2.7
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli-strive
  repository: null
  sc: git
  workspace_type: Application
